// Alt text for every photo the site uses (written from the photos, 2026-09-26).
// Key = "<project folder>/<file>". Anything missing falls back to "<Project> by IKDU".
// Building-type icons: their alt text comes from the category labels in site.js (IKDU_CATS),
// e.g. "Villas — filter projects". Legend/chip icons next to a visible label use alt="" (the label is the text).
window.IKDU_ALT = {
  "twin-villas/20230329_105857.jpg": "Twin Villas living room before finishing: bare plaster walls, exposed conduit and a wheelbarrow",
  "twin-villas/20230329_110039.jpg": "Twin Villas entrance before finishing: rough columns and unfinished steps",
  "twin-villas/20230329_110331.jpg": "Twin Villas bathroom wall before finishing: raw blockwork around the tiled niches",
  "twin-villas/20230329_110336.jpg": "Twin Villas bathroom during works: niches formed in the stone-look tiled wall",
  "twin-villas/WhatsApp_Image_2026-09-16_at_13.19.42.jpg": "Twin Villas bathroom stripped back to rubble and blockwork",
  "twin-villas/DSC01968.jpg": "Twin Villas finished bathroom: grey stone-look tiles, lit niches with towels and a freestanding tub",
  "twin-villas/DSC01954.jpg": "Twin Villas upper hallway: panelled doors, a built-in cupboard and a lit ceiling cove",
  "twin-villas/DSC02001.jpg": "Twin Villas finished living room: herringbone parquet, dark timber shelving and a garden view",
  "twin-villas/DSC02011.jpg": "Twin Villas living room with herringbone parquet, timber shelving and a view through to the front door",
  "twin-villas/DSC02012.jpg": "Twin Villas living room: herringbone parquet floor, sofa and cove lighting",
  "twin-villas/DSC02021.jpg": "Twin Villas garden façade: stone-clad terrace, steps and a palm tree",
  "twin-villas/DSC02028.jpg": "Twin Villas entrance: stone columns, iron gate and a solid timber front door",
  "twin-villas/DSC01964.jpg": "Twin Villas master bedroom: dark timber wardrobe with a mirror door and a cove-lit ceiling",
  "twin-villas/DSC01980.jpg": "Twin Villas family room: corner sofa under a cove-lit ceiling",
  "twin-villas/DSC01988.jpg": "Twin Villas roof terrace: stone balustrade with a view over Legenda",
  "twin-villas/DSC01948.jpg": "Twin Villas bathroom: 3D wall tiles, backlit mirror and a vessel basin",
  "twin-villas/DSC01972.jpg": "Twin Villas bathroom in dark stone: built-in niches, bathtub and walk-in shower",
  "twin-villas/IMG_3421.jpg": "Twin Villas finished entrance: stone columns, new steps and the timber front door",
  "m-villa/20230827_214202.jpg": "M-Villa ground floor before finishing: bare concrete and rubble",
  "m-villa/20230917_135241.jpg": "M-Villa during works: rubble bags and raw concrete walls",
  "m-villa/20230917_135258.jpg": "M-Villa staircase before finishing: raw concrete stair",
  "m-villa/DSC09366.jpg": "M-Villa ground floor: open living space with a grey marble floor, lit staircase with a timber slat screen and garden doors",
  "m-villa/DSC09375.jpg": "M-Villa finished staircase: marble treads, timber slat screen and hidden step lighting",
  "m-villa/DSC09518.jpg": "M-Villa hidden door closed: flush with the full-height timber slat wall",
  "m-villa/DSC09527.jpg": "M-Villa hidden door open in the timber slat wall",
  "m-villa/DSC09599.jpg": "M-Villa open-plan ground floor: marble floor, kitchen and the slatted staircase",
  "m-villa/DSC09644.jpg": "M-Villa reception: polished marble floor and recessed ceiling lighting",
  "m-villa/DSC09722.jpg": "M-Villa upper landing: timber balustrade and wood floor",
  "m-villa/DSC09755-1.jpg": "Close-up of the M-Villa timber slats over marble stair treads",
  "m-villa/DSC09712.jpg": "M-Villa guest bathroom: backlit mirror, stone vanity with a vessel basin and a wall-hung toilet",
  "m-villa/DSC09530-HDR-2.jpg": "M-Villa bathroom under the stairs: long grey marble vanity, marble floor and a mirror at the end",
  "m-villa/DSC09717.jpg": "M-Villa upper hallway: marble floor, timber doors and the slatted wooden balustrade",
  "polysh/20241104_193756.jpg": "Polysh before fit-out: bare concrete shell with brick walls",
  "polysh/20241228_063515.jpg": "Polysh during fit-out: installing walls and services",
  "polysh/DSC02600.jpg": "Polysh waiting lounge: curved sofa, terracotta niche shelving, chain curtain and the \"You just got Polyshed\" sign",
  "polysh/20260510_215836.jpg": "Polysh massage room: warm timber walls, lit ceiling and the Polysh sign",
  "polysh/DSC02597.jpg": "Polysh manicure stations behind the terracotta shelving screen",
  "polysh/DSC02608.jpg": "Polysh reception: curved terracotta desk in front of a copper chain curtain with the Polysh sign",
  "polysh/DSC02619.jpg": "Polysh pedicure chairs and manicure stations with lit display shelves",
  "polysh/DSC02639.jpg": "Polysh salon floor: manicure stations and pedicure chairs under arched niches",
  "polysh/DSC02645.jpg": "Polysh manicure stations with warm linear lighting and terracotta walls",
  "polysh/IMG_1862.jpg": "Polysh detail: terracotta plaster wall and slim niche shelving",
  "polysh/IMG_0959.jpg": "Polysh shopfront: glass façade and the Polysh sign on a terracotta wall",
  "s-roof/DSC00011.jpg": "Sodic rooftop: timber-screened outdoor kitchen under a clear sky",
  "s-roof/DSC00057.jpg": "Sodic rooftop: white walls, outdoor kitchen counter and timber screens",
  "s-roof/DSC09885.jpg": "Sodic rooftop lounge under the white pergola with oak battens",
  "s-roof/DSC09930.jpg": "Sodic rooftop: white pergola with oak battens over a built-in lounge",
  "s-roof/DSC09938.jpg": "Sodic rooftop outdoor kitchen: timber cabinets and louvred storage, table tucked away",
  "s-roof/DSC09947.jpg": "Sodic rooftop outdoor kitchen with the rotating table swung out",
  "s-roof/IMG-20251218-WA0024.jpg": "Sodic rooftop during works: bare steel pergola frame",
  "s-roof/IMG-20251230-WA0007.jpg": "Sodic rooftop during works: pergola frame with battens going up",
  "s-roof/IMG_1016.jpg": "Sodic rooftop at dusk: pergola and built-in lounge with hidden LED lighting",
  "sane/20250712_013724.jpg": "Sane during works: the circular path set out on site at night",
  "sane/20250712_200146.jpg": "Sane during works: the circular path poured in concrete",
  "sane/20250823-DSC04416-Edit.jpg": "Sane art room: giraffe table and shelving wall made by IKDU, children working with a teacher",
  "sane/8379CE78-E7CE-4747-A89E-ADBB7ABB8C41_1_201_a.jpg": "Sane garden from above: turf, timber fencing and a round play table",
  "sane/C361BE98-8ECD-4E9E-B90A-B857DB3771C2_1_201_a.jpg": "Sane garden classroom: circular planter with a tree, turf, timber fencing and play furniture",
  "sane/new-2.jpg": "Sane: custom timber seat with cushions",
  "sane/new.jpg": "Sane: timber shelving wall with art supplies",
  // Connect page close-ups
  "connect/mirror-ceiling.jpg": "Close-up of the mirror mosaic ceiling at Polysh",
  "connect/polysh-terracotta-lattice.jpg": "Close-up of the terracotta wall and timber lattice at Polysh",
  "connect/polysh-chain-curtain.jpg": "Close-up of the copper chain curtain and cove light at Polysh",
  "connect/polysh-fluted-wall.jpg": "Close-up of a fluted wall finish at Polysh",
  "connect/polysh-fluted-texture.jpg": "Close-up of fluted wall texture at Polysh",
  "connect/polysh-fluted-wall-2.jpg": "Close-up of fluted wall panels at Polysh",
  "connect/polysh-fluted-corner.jpg": "Close-up of a fluted wall corner at Polysh",
  "connect/sodic-roof-1034.jpg": "Close-up of timber screen slats against the sky, Sodic rooftop",
  "connect/sodic-roof-1035.jpg": "Sodic rooftop pergola seen from the lounge",
  "connect/sodic-roof-1036.jpg": "Pergola slats seen from below, Sodic rooftop",
  "connect/sodic-roof-1037.jpg": "Pergola battens seen from below, Sodic rooftop",
  "connect/sodic-roof-1038.jpg": "White pergola frame and timber battens against the sky, Sodic rooftop",
  "connect/sodic-roof-1039.jpg": "White pergola frame with timber battens, Sodic rooftop"
};
// On Arabic pages (lang="ar") the Arabic text in alt-ar.js is used; English is never shown there.
window.ikduAlt = (key, fallback) => (document.documentElement.lang === "ar" ? (window.IKDU_ALT_AR || {})[key] : window.IKDU_ALT[key]) || fallback || "";
